server:
  port: 8082

spring:
  application:
    name: tracking-service

  datasource:
    url: jdbc:postgresql://localhost:5433/tracking_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
       spring.json.type.mapping:
        locationUpdatedEvent:com.umutgldn.tracking_service.event.LocationUpdatedEvent,milestoneReachedEvent:com.umutgldn.tracking_service.event.MilestoneReachedEvent

route-service:
  url: http://localhost:8081

simulation:
  tick-interval-ms: 5000
  step: 10
  max-consecutive-failures: 5

logging:
  level:
    com.umutgldn.tracking_service: INFO
    org.hibernate.SQL: WARN

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true